pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub-creds'  
        FRONTEND_TAG = 'frontend2'
        DOCKERHUB_USERNAME = 'omarismail0'            
        DOCKERHUB_REPOSITORY = 'kubernetes-project'   
    }
    stages {
        
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }       

        stage('Build Frontend Image') {
            steps {
                dir('frontend'){
                    script {
                        //docker.build("${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${FRONTEND_TAG}", "-f ./frontend/ .")
                        def frontendImage = docker.build("${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${FRONTEND_TAG}")
                        docker.withRegistry('', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image(frontendImage).push()
                        }
                    }
                }
            }
        }


        stage('Apply Kubernetes Manifests') {
            steps {
                sh '''
                set -e
                export KUBECONFIG=~/.kube/config
                sudo kubectl apply -f k8s/FrontendDeployment.yaml --validate=false
                '''
            }
        }

       
    }
    post {
        always {
            cleanWs()
        }
    }
}
